pipeline {
    agent { label 'rpi2' }
    environment {
        toEmail = 'carloesanchez@gmail.com'
        fromEmail = 'jenkins@rpi2-local.edu'
        backupLocation = '/home/pi/Downloads'
        hostName = 'rpi2'
    }

    stages {
        stage('build') {
            steps {
                    withCredentials([usernamePassword(credentialsId: 'jenkins_on_rpi', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh script: '''dirToScan=${backupLocation}
                    echo "Attempting to run ClamAV against "$dirToScan

                    cd $dirToScan
                    pwd

                    echo $PASSWORD | sudo -S virus-scan''',
                    label: 'runVirusScan'
                    }
                }
        }
        stage('notification'){
            steps {
                    emailext attachLog: true,
                    body: "Virus Scan ran against ${backupLocation} on ${hostName} /n
                    More info at ${env.BUILD_URL}", 
                    subject: 'Virus Scan Completed', 
                    to: "${toEmail}"
            }
        }
    }
}
