pipeline {
    agent { label 'rpi' }
    environment {
        toEmail = 'carloesanchez@gmail.com'
        fromEmail = 'jenkins@rpi-local.edu'
        backupLocation = '/home/pi'
        hostName = 'rpi'
    }

    stages {
        stage('build') {
            steps {
                    withCredentials([usernamePassword(credentialsId: 'jenkins_on_rpi', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh script: '''dirToScan=${backupLocation}
                    echo "Attempting to run ClamAV against "$dirToScan

                    cd $dirToScan
                    pwd

                    echo $PASSWORD | sudo -S virus-scan''',
                    label: 'runVirusScan'
                    }
                }
        }
        stage('notification'){
            steps {
                mail bcc: '',
                body: "Virus Scan ran against ${backupLocation} on ${hostName}",
                cc: '',
                from: "${fromEmail}",
                replyTo: '',
                subject: 'Virus Scan Completed',
                to: "${toEmail}"
            }
        }
    }
}
