pipeline {
    agent any
    stages {
        stage('build') {
            steps {
		sh label: 'runVirusScan', script: '''dirToScan="/home/carlo"
		echo "Attempting to run ClamAV against "$dirToScan

		cd $dirToScan
		pwd

		virus-scan'''
            }
        }
	stage('notification'){
		steps {
		mail bcc: '', body: 'Virus Scan ran against ubuntu home folder', cc: '', from: 'carloesanchez@gmail.com', replyTo: '', subject: 'Virus Scan Completed', to: 'carloesanchez@gmail.com'
		}
	}
    }
}
