pipeline {
    agent any
    environment {
        toEmail = 'carloesanchez@gmail.com'
        fromEmail = 'jenkins@ubuntu-local.edu'
        backupLocation = '/home/pi'
        hostName = 'RPi'
    }

    stages {
        stage('build') {
            steps {
                    sh script: '''dirToScan=${backupLocation}
                    echo "Attempting to run ClamAV against "$dirToScan

                    cd $dirToScan
                    pwd

                    virus-scan''',
                    label: 'runVirusScan'
                }
        }
        stage('notification'){
            steps {
                mail bcc: '',
                body: "Virus Scan ran against ${backupLocation} on ${hostName}",
                cc: '',
                from: "${fromEmail}",
                replyTo: '',
                subject: 'Virus Scan Completed',
                to: "${toEmail}"
            }
        }
    }
}
