pipeline {
    agent any
    environment {
        toEmail = 'carloesanchez@gmail.com'
        fromEmail = 'jenkins@ubuntu-local.edu'
        backupLocation = '/home/carlo/Downloads'
    }

    stages {
        stage('build') {
            steps {
                    sh, 
                    label: 'runVirusScan',
                    script: '''dirToScan="'''"${backupLocation}"'''"
                    echo "Attempting to run ClamAV against "$dirToScan

                    cd $dirToScan
                    pwd

                    virus-scan'''
                }
        }
        stage('notification'){
            steps {
                mail bcc: '',
                body: 'Virus Scan ran against ubuntu Downloads folder',
                cc: '',
                from: "${fromEmail}",
                replyTo: '',
                subject: 'Virus Scan Completed',
                to: "${toEmail}"
            }
        }
    }
}
